// src/routes/quizzes/guess-the-note.tsx
import {createFileRoute} from '@tanstack/react-router'
import GuitarNeck from "@/components/GuitarNeck.tsx";
import {useState} from "react";
import {GuitarNeckEStandardTuning, StringNote} from "@/types/GuitarNeckEStandardTuning.ts";
import {PITCH_CLASS_NAMES} from "@/types/Note.ts";

export const Route = createFileRoute('/quizzes/guess-the-note')({
    component: RouteComponent,
})

const STARTS_AT_FRET = 0
const NUMBER_OF_FRETS = 3

function getRandomNote(numberOfFrets: number, startFret: number): StringNote {
    const stringIndex = Math.floor(Math.random() * 6);
    const fretNumber = Math.floor(Math.random() * numberOfFrets) + startFret;

    const note = GuitarNeckEStandardTuning[stringIndex][fretNumber];
    return {stringIndex, note};
}

function RouteComponent() {
    const [selectedStartFret, setSelectedStartFret] = useState<number>(STARTS_AT_FRET);
    const [selectedNumberOfFrets, setSelectedNumberOfFrets] = useState<number>(NUMBER_OF_FRETS);
    const [selectedNotes, setSelectedNotes] = useState<StringNote[]>([getRandomNote(selectedNumberOfFrets, selectedStartFret)])
    const [score, setScore] = useState<{ correct: number; total: number }>({correct: 0, total: 0});
    const [incorrectNotes, setIncorrectNotes] = useState<StringNote[]>([]);

    return (
        <div className="p-4 bg-white rounded shadow-md mx-10 mt-10 flex flex-col items-center">
            <h2 className="text-lg font-semibold mb-3">Guess the Note Quiz</h2>

            <div>
                <div>
                    <label htmlFor="number-of-frets">Number of Frets: </label>
                    <select
                        id="number-of-frets"
                        value={selectedNumberOfFrets}
                        onChange={(e) => {
                            const numFrets = parseInt(e.target.value, 10);
                            setSelectedNumberOfFrets(numFrets);
                            // reset the note
                            setSelectedNotes([getRandomNote(selectedNumberOfFrets, selectedStartFret)]);
                        }}
                        className="border p-1 rounded mb-4"
                    >
                        {[1, 2, 3, 4, 5, 6].map((num) => (
                            <option key={num} value={num}>
                                {num}
                            </option>
                        ))}
                    </select>
                </div>

                <div>
                    <label htmlFor="starting-fret">Starting fret: </label>
                    <select
                        id="starting-fret"
                        value={selectedStartFret}
                        onChange={(e) => {
                            const startFret = parseInt(e.target.value, 10);
                            setSelectedStartFret(startFret);
                            // reset the note
                            setSelectedNotes([getRandomNote(selectedNumberOfFrets, selectedStartFret)]);
                        }}
                        className="border p-1 rounded mb-4"
                    >
                        {[0, 1, 2, 3].map((num) => (
                            <option key={num} value={num}>
                                {num}
                            </option>
                        ))}
                    </select>
                </div>
            </div>

            <GuitarNeck
                selectedNotes={selectedNotes}
                setSelectedNotes={setSelectedNotes}
                startsAtFret={selectedStartFret}
                numberOfFrets={selectedNumberOfFrets}
                displayNoteLabels={false}
            />

            <div>
                {PITCH_CLASS_NAMES.map((pc) => (
                    <button
                        key={pc}
                        onClick={() => {
                            const currentNote = selectedNotes[0].note;
                            if (currentNote.canonicalName === pc) {
                                alert(`Correct! The note is ${currentNote.toString()}`);
                                setScore(({correct, total}) => ({correct: correct + 1, total: total + 1}));
                            } else {
                                alert(`Incorrect. The note is ${currentNote.toString()}`);
                                setScore(({correct, total}) => ({correct, total: total + 1}));
                                setIncorrectNotes((prev) => [...prev, selectedNotes[0]]);
                            }
                            setSelectedNotes([getRandomNote(selectedNumberOfFrets, selectedStartFret)]);
                        }}
                        className="m-1 p-2 bg-gray-200 rounded hover:bg-gray-300"
                    >
                        {pc}
                    </button>
                ))}
            </div>

            <div className="mt-4">
                Score: {score.correct} / {score.total}
            </div>

            {incorrectNotes.length > 0 && (
                <div className="mt-4">
                    <h3 className="font-medium">Incorrect Notes:</h3>
                    <ul>
                        {incorrectNotes.map((note, index) => (
                            <li key={index}>
                                String {note.stringIndex + 1}, Note: {note.note.toString()}
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    )
}

// src/routes/quizzes/guess-the-note/+page.svelte
<script lang="ts">
	import GuitarNeck from '$lib/components/GuitarNeck.svelte';
	import { GuitarNeckEStandardTuning, type StringNote } from '$types/GuitarNeckEStandardTuning';
	import { PITCH_CLASS_NAMES } from '$types/Note';

	let startsAtFret = $state(0);
	let numberOfFrets = $state(3);
	let score = $state({ correct: 0, total: 0 });
	let incorrectNotes = $state<StringNote[]>([]);
	let feedback = $state<{ text: string; correct: boolean } | null>(null);
	let guessLocked = $state(false);

	function getRandomNote(): StringNote {
		const stringIndex = Math.floor(Math.random() * 6);
		const fretNumber = Math.floor(Math.random() * numberOfFrets) + startsAtFret;
		return { stringIndex, note: GuitarNeckEStandardTuning[stringIndex][fretNumber] };
	}

	let currentNote = $state(getRandomNote());

	function guess(pc: string) {
		if (guessLocked) return;
		guessLocked = true;

		const correct = currentNote.note.canonicalName === pc;

		if (correct) {
			feedback = { text: `Correct! — ${currentNote.note.toString()}`, correct: true };
			score = { correct: score.correct + 1, total: score.total + 1 };
		} else {
			feedback = { text: `Incorrect — ${currentNote.note.toString()}`, correct: false };
			score = { ...score, total: score.total + 1 };
			incorrectNotes = [...incorrectNotes, currentNote];
		}

		setTimeout(() => {
			currentNote = getRandomNote();
			feedback = null;
			guessLocked = false;
		}, 1200);
	}

	function onStartFretChange(e: Event) {
		startsAtFret = parseInt((e.target as HTMLSelectElement).value, 10);
		currentNote = getRandomNote();
	}

	function onNumFretsChange(e: Event) {
		numberOfFrets = parseInt((e.target as HTMLSelectElement).value, 10);
		currentNote = getRandomNote();
	}
</script>

<svelte:head>
	<title>Fretboard — Guess the Note</title>
</svelte:head>

<div class="quiz">
	<h2>Guess the Note</h2>

	<div class="controls">
		<label>
			Starting fret
			<select value={startsAtFret} onchange={onStartFretChange}>
				{#each [0, 1, 2, 3] as n}
					<option value={n}>{n}</option>
				{/each}
			</select>
		</label>

		<label>
			Number of frets
			<select value={numberOfFrets} onchange={onNumFretsChange}>
				{#each [1, 2, 3, 4, 5, 6] as n}
					<option value={n}>{n}</option>
				{/each}
			</select>
		</label>
	</div>

	<div class="neck-container">
		<GuitarNeck
			selectedNotes={[currentNote]}
			{startsAtFret}
			{numberOfFrets}
			displayNoteLabels={false}
		/>
	</div>

	<div class="pitch-buttons">
		{#each PITCH_CLASS_NAMES as pc}
			<button onclick={() => guess(pc)} disabled={guessLocked}>{pc}</button>
		{/each}
	</div>

	{#if feedback}
		<div class="feedback" class:correct={feedback.correct} class:incorrect={!feedback.correct}>
			{feedback.text}
		</div>
	{:else}
		<div class="feedback-placeholder"></div>
	{/if}

	<div class="score">Score: {score.correct} / {score.total}</div>

	{#if incorrectNotes.length > 0}
		<div class="incorrects">
			<h3>Incorrect Notes</h3>
			<ul>
				{#each incorrectNotes as n}
					<li>String {n.stringIndex + 1}: {n.note.toString()}</li>
				{/each}
			</ul>
		</div>
	{/if}
</div>

<style>
	.quiz {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 1.5rem;
	}

	h2 {
		margin: 0;
		font-size: 1.4rem;
		font-weight: 600;
		color: #f1f5f9;
	}

	.controls {
		display: flex;
		gap: 2rem;
		flex-wrap: wrap;
		justify-content: center;
	}

	label {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		font-size: 0.9rem;
		color: #94a3b8;
	}

	select {
		background: #1e293b;
		color: #e2e8f0;
		border: 1px solid #475569;
		border-radius: 4px;
		padding: 0.3rem 0.5rem;
		font-family: inherit;
	}

	.neck-container {
		width: 100%;
		overflow-x: auto;
		display: flex;
		justify-content: center;
	}

	.pitch-buttons {
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
		gap: 0.4rem;
		max-width: 440px;
	}

	.pitch-buttons button {
		padding: 0.5rem 0.9rem;
		min-width: 52px;
		background: #1e293b;
		color: #e2e8f0;
		border: 1px solid #334155;
		border-radius: 6px;
		cursor: pointer;
		font-size: 0.9rem;
		font-family: inherit;
		transition:
			background 0.12s,
			border-color 0.12s;
	}

	.pitch-buttons button:hover:not(:disabled) {
		background: #334155;
		border-color: #475569;
	}

	.pitch-buttons button:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.feedback {
		padding: 0.5rem 1.5rem;
		border-radius: 6px;
		font-weight: 500;
		font-size: 0.95rem;
	}

	.feedback-placeholder {
		height: 2rem;
	}

	.correct {
		background: #052e16;
		color: #4ade80;
		border: 1px solid #16a34a;
	}

	.incorrect {
		background: #2d0a0a;
		color: #f87171;
		border: 1px solid #991b1b;
	}

	.score {
		font-size: 1rem;
		color: #64748b;
	}

	.incorrects {
		width: 100%;
		max-width: 400px;
	}

	.incorrects h3 {
		margin: 0 0 0.4rem;
		font-size: 0.85rem;
		font-weight: 500;
		color: #64748b;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.incorrects ul {
		list-style: disc;
		padding-left: 1.25rem;
		margin: 0;
		font-size: 0.875rem;
		color: #475569;
	}

	.incorrects li {
		margin: 0.2rem 0;
	}
</style>
